const fs = require("node:fs/promises");
const express = require("express");
const { pushConversationMessage } = require("../store/conversationStore");
const { getLastCreatedRecipeId } = require("../store/lastRecipeByUser");
const { recipeStore } = require("../store/recipeStore");
const {
	uploadRecipeToCookidooAccount,
	uploadCookidooNativeToAccount,
} = require("../services/cookidooUpload");
const {
	validateRecipeForUpload,
	isStoredRecipeUsable,
	recipeToUploadPayload,
} = require("../utils/validateRecipe");
const { runChatTurn } = require("../services/chatTurn");

/**
 * REST API for the mobile app (app-mimi-mobile). Channel-agnostic twin of the
 * WhatsApp webhook: same stores and recipe AI, JSON in/out instead of Meta payloads.
 * `userId` is an opaque per-install id generated by the app.
 */
function createApiRouter({ config, recipeAi }) {
	const router = express.Router();

	async function hasCookidooCredentials() {
		try {
			await fs.access(config.cookidooCredentialsPath);
			const hasCookieEnv = Boolean(
				process.env.COOKIDOO_COOKIE_HEADER?.trim() ||
					process.env.COOKIDOO_COOKIES_JSON?.trim(),
			);
			if (!hasCookieEnv) {
				await fs.access(config.cookidooCookiesPath);
			}
			return true;
		} catch {
			return false;
		}
	}

	router.get("/health", (_req, res) => {
		res.json({ ok: true });
	});

	router.post("/chat", async (req, res) => {
		const userId = String(req.body?.userId || "").trim();
		const message = String(req.body?.message || "").trim();

		if (!userId || !message) {
			return res
				.status(400)
				.json({ error: "userId y message son obligatorios" });
		}

		try {
			pushConversationMessage(userId, "user", message);
			const {
				proposal: reply,
				isComplete,
				prepError,
			} = await runChatTurn(userId, recipeAi, { channel: "app" });

			if (!isComplete) {
				return res.json({ reply, recipeReady: false });
			}

			if (prepError) {
				console.error("Preparar receta Cookidoo (api):", prepError);
				return res.json({ reply, recipeReady: false });
			}

			const recipeId = getLastCreatedRecipeId(userId);
			return res.json({ reply, recipeReady: true, recipeId });
		} catch (error) {
			console.error("Error en /api/chat:", error);
			return res.status(502).json({
				error:
					"Tuve un problema generando la respuesta. Inténtalo de nuevo con más detalle.",
			});
		}
	});

	router.get("/recipes/:id", (req, res) => {
		const stored = recipeStore.get(req.params.id);
		if (!stored) {
			return res.status(404).json({ error: "Receta no encontrada" });
		}
		// cookidooNative es el payload crudo de Cookidoo (grande e irrelevante para la UI)
		const { cookidooNative, ...recipe } = stored;
		return res.json(recipe);
	});

	router.post("/recipes/:id/upload", async (req, res) => {
		const stored = recipeStore.get(req.params.id);
		if (!stored) {
			return res.status(404).json({ error: "Receta no encontrada" });
		}

		if (!(await hasCookidooCredentials())) {
			return res.status(503).json({
				error:
					"Falta la sesión de Cookidoo en el servidor (COOKIDOO_COOKIE_HEADER).",
			});
		}

		try {
			let recipeUrl;
			let title;

			if (stored.cookidooNative?.content) {
				const result = await uploadCookidooNativeToAccount(
					stored.cookidooNative,
					config.cookidooCredentialsPath,
					config.cookidooCookiesPath,
				);
				recipeUrl = result.recipeUrl;
				title = stored.cookidooNative.content.name || stored.title || "Receta";
			} else {
				if (!isStoredRecipeUsable(stored)) {
					return res
						.status(409)
						.json({ error: "La receta guardada está incompleta" });
				}
				const recipe = recipeToUploadPayload(stored);
				validateRecipeForUpload(recipe);
				const result = await uploadRecipeToCookidooAccount(
					recipe,
					config.cookidooCredentialsPath,
					config.cookidooCookiesPath,
				);
				recipeUrl = result.recipeUrl;
				title = recipe.title;
			}

			return res.json({ title, recipeUrl });
		} catch (cookidooError) {
			console.error("Cookidoo upload error (api):", cookidooError);
			return res.status(502).json({
				error: `No pude subir la receta a Cookidoo: ${cookidooError.message}`,
			});
		}
	});

	return router;
}

module.exports = { createApiRouter };
