const fs = require("node:fs/promises");
const express = require("express");
const { pushConversationMessage } = require("../store/conversationStore");
const { recipeStore } = require("../store/recipeStore");
const {
	uploadRecipeToCookidooAccount,
	uploadCookidooNativeToAccount,
} = require("../services/cookidooUpload");
const {
	validateRecipeForUpload,
	isStoredRecipeUsable,
	recipeToUploadPayload,
} = require("../utils/validateRecipe");
const { runChatTurn } = require("../services/chatTurn");
const {
	seedCookidooUrlIfPresent,
	seedCookidooImagesIfPresent,
} = require("../services/cookidooImport");
const { looksLikeCookidooUrl } = require("../services/cookidooParse");

/** Tope de capturas por mensaje (una receta rara vez ocupa más pantallas). */
const MAX_IMAGES = 10;

/**
 * Valida y limpia `images` del body: solo strings que sean data URLs de imagen
 * (`data:image/…;base64,…`) o URLs http(s). Descarta el resto y limita el total.
 */
function normalizeImages(raw) {
	if (!Array.isArray(raw)) {
		return [];
	}
	return raw
		.map((img) => (typeof img === "string" ? img.trim() : ""))
		.filter(
			(img) =>
				/^data:image\/[a-z0-9.+-]+;base64,/i.test(img) ||
				/^https?:\/\//i.test(img),
		)
		.slice(0, MAX_IMAGES);
}

/**
 * REST API for the mobile app (app-mimi-mobile). Channel-agnostic twin of the
 * WhatsApp webhook: same stores and recipe AI, JSON in/out instead of Meta payloads.
 * `userId` is an opaque per-install id generated by the app.
 */
function createApiRouter({ config, recipeAi }) {
	const router = express.Router();

	async function hasCookidooCredentials() {
		try {
			await fs.access(config.cookidooCredentialsPath);
			const hasCookieEnv = Boolean(
				process.env.COOKIDOO_COOKIE_HEADER?.trim() ||
					process.env.COOKIDOO_COOKIES_JSON?.trim(),
			);
			if (!hasCookieEnv) {
				await fs.access(config.cookidooCookiesPath);
			}
			return true;
		} catch {
			return false;
		}
	}

	router.get("/health", (_req, res) => {
		res.json({ ok: true });
	});

	router.post("/chat", async (req, res) => {
		const userId = String(req.body?.userId || "").trim();
		const message = String(req.body?.message || "").trim();
		const images = normalizeImages(req.body?.images);

		if (!userId) {
			return res.status(400).json({ error: "userId es obligatorio" });
		}
		if (!message && images.length === 0) {
			return res
				.status(400)
				.json({ error: "Envía un mensaje o al menos una captura" });
		}

		const wantsStream =
			String(req.headers.accept || "").includes("ndjson") ||
			String(req.query.stream || "") === "1";

		const emit = (event) => {
			if (!wantsStream || res.writableEnded) {
				return;
			}
			res.write(`${JSON.stringify(event)}\n`);
		};

		if (wantsStream) {
			res.status(200);
			res.setHeader("Content-Type", "application/x-ndjson; charset=utf-8");
			res.setHeader("Cache-Control", "no-cache, no-transform");
			res.setHeader("Connection", "keep-alive");
			res.setHeader("X-Accel-Buffering", "no");
			res.flushHeaders();
		}

		try {
			if (images.length > 0) {
				try {
					await seedCookidooImagesIfPresent({
						userId,
						images,
						extraInstruction: message,
						recipeAi,
					});
				} catch (importError) {
					console.error("Importar capturas Cookidoo (api):", importError);
					const errorText = `No pude leer esa receta de las capturas: ${importError.message}`;
					if (wantsStream) {
						emit({ type: "error", error: errorText });
						emit({ type: "done" });
						return res.end();
					}
					return res.status(502).json({ error: errorText });
				}
			} else {
				pushConversationMessage(userId, "user", message);

				if (looksLikeCookidooUrl(message)) {
					try {
						await seedCookidooUrlIfPresent({
							userId,
							userText: message,
							credentialsPath: config.cookidooCredentialsPath,
							cookiesPath: config.cookidooCookiesPath,
						});
					} catch (importError) {
						console.error("Importar URL Cookidoo (api):", importError);
						const errorText = `No pude leer esa receta de Cookidoo: ${importError.message}`;
						if (wantsStream) {
							emit({ type: "error", error: errorText });
							emit({ type: "done" });
							return res.end();
						}
						return res.status(502).json({ error: errorText });
					}
				}
			}

			const {
				proposal: reply,
				isComplete,
				prepError,
				recipeId,
			} = await runChatTurn(userId, recipeAi, {
				channel: "app",
				onEvent: wantsStream ? emit : undefined,
			});

			if (wantsStream) {
				if (isComplete && prepError) {
					console.error("Preparar receta Cookidoo (api):", prepError);
					emit({
						type: "error",
						error:
							"No pude preparar la receta para Cookidoo. Inténtalo de nuevo en un momento.",
					});
				}
				emit({ type: "done" });
				return res.end();
			}

			if (!isComplete) {
				return res.json({ reply, recipeReady: false });
			}

			if (prepError) {
				console.error("Preparar receta Cookidoo (api):", prepError);
				return res.json({
					reply: `${reply}\n\n(No pude preparar la receta para Cookidoo. Inténtalo de nuevo en un momento.)`,
					recipeReady: false,
				});
			}

			if (!recipeId) {
				console.error("Receta completa pero sin recipeId (api)");
				return res.json({ reply, recipeReady: false });
			}
			return res.json({ reply, recipeReady: true, recipeId });
		} catch (error) {
			console.error("Error en /api/chat:", error);
			if (wantsStream) {
				emit({
					type: "error",
					error:
						"Tuve un problema generando la respuesta. Inténtalo de nuevo con más detalle.",
				});
				emit({ type: "done" });
				return res.end();
			}
			return res.status(502).json({
				error:
					"Tuve un problema generando la respuesta. Inténtalo de nuevo con más detalle.",
			});
		}
	});

	router.get("/recipes/:id", (req, res) => {
		const stored = recipeStore.get(req.params.id);
		if (!stored) {
			return res.status(404).json({ error: "Receta no encontrada" });
		}
		// cookidooNative es el payload crudo de Cookidoo (grande e irrelevante para la UI)
		const { cookidooNative, ...recipe } = stored;
		return res.json(recipe);
	});

	router.post("/recipes/:id/upload", async (req, res) => {
		const stored = recipeStore.get(req.params.id);
		if (!stored) {
			return res.status(404).json({ error: "Receta no encontrada" });
		}

		if (!(await hasCookidooCredentials())) {
			return res.status(503).json({
				error:
					"Falta la sesión de Cookidoo en el servidor (COOKIDOO_COOKIE_HEADER).",
			});
		}

		try {
			let recipeUrl;
			let title;

			if (stored.cookidooNative?.content) {
				const result = await uploadCookidooNativeToAccount(
					stored.cookidooNative,
					config.cookidooCredentialsPath,
					config.cookidooCookiesPath,
				);
				recipeUrl = result.recipeUrl;
				title = stored.cookidooNative.content.name || stored.title || "Receta";
			} else {
				if (!isStoredRecipeUsable(stored)) {
					return res
						.status(409)
						.json({ error: "La receta guardada está incompleta" });
				}
				const recipe = recipeToUploadPayload(stored);
				validateRecipeForUpload(recipe);
				const result = await uploadRecipeToCookidooAccount(
					recipe,
					config.cookidooCredentialsPath,
					config.cookidooCookiesPath,
				);
				recipeUrl = result.recipeUrl;
				title = recipe.title;
			}

			return res.json({ title, recipeUrl });
		} catch (cookidooError) {
			console.error("Cookidoo upload error (api):", cookidooError);
			return res.status(502).json({
				error: `No pude subir la receta a Cookidoo: ${cookidooError.message}`,
			});
		}
	});

	return router;
}

module.exports = { createApiRouter };
